### PR TITLE
Upgrade Django to 2.2.4 for security fixes

### PR DESCRIPTION
**Pull request by stevenday**
Github was bugging me while working on #40 and whilst I don't think there's any real security risk from it (presumably any including project sets its own Django version and is more on top of any version bumps) - it's nice to reduce noise so we can see any real issues.

### CODE REVIEW

**Comment by stevenday** [comment]
@Bjwebb @odscjames - I just picked one of you at random for a review of this too, feel free to reassign as you see fit.

**Comment by odscjames** [comment]
Thanks - can we put on hold while we consider #40 ? It's possible the solution to that may remove the need for this entirely, or actually do this upgrade at the same time.

**Comment by stevenday** [comment]
> Thanks - can we put on hold while we consider #40 ? It's possible the solution to that may remove the need for this entirely, or actually do this upgrade at the same time.

Sure 👍

**Comment by stevenday** [comment]
Closing this as #40 now has a different spec for Django in setup.py and 2.2.4 is itself out of date, with dependabot adding an auto PR for 2.2.8.

**Pull request closed without merging**
